version: '2'
services:
  mysql:
    image: mysql:5.7
    volumes:
      - "./docker/mysql:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=question_box
      - MYSQL_USER=question_box
      - MYSQL_PASSWORD=m3EZSbGD
    ports:
      - "3306:3306"

  php:
    build: ./docker/php 
    volumes:
      - ".:/var/www/html"
      - "./docker/php/default.conf:/etc/apache2/sites-available/000-default.conf"
    ports:
      - 8000:80
    links:
      - mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=root
    links:
      - mysql
    ports:
       - 8080:80

  node:
    build: ./docker/node
    ports:
      - 3000:3000
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    command: /bin/sh
